---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/cancel":
    get:
      summary: cancel registration
      responses:
        '200':
          description: successful
  "/api/v1/auth/sign_up":
    get:
      summary: new registration
      responses:
        '200':
          description: successful
  "/api/v1/auth/edit":
    get:
      summary: edit registration
      responses:
        '200':
          description: successful
  "/api/v1/auth":
    patch:
      summary: update registration
      responses:
        '200':
          description: successful
    put:
      summary: update registration
      responses:
        '200':
          description: successful
    delete:
      summary: delete registration
      responses:
        '200':
          description: successful
    post:
      summary: create registration
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
securityDefinitions:
  Bearer:
    description: ''
    type: apiKey
    name: Authorization
    in: header
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
